### ISSUE TITLE
functions lib addition

### ISSUE THREAD

**Issue by woodwardtw** [lceberg/Vuetiful#1]
It might be my install, but I had to change line 3 of functions.php to 

`! defined( 'VUETIFUL_MODULES_DIR' ) ? define( 'VUETIFUL_MODULES_DIR', get_template_directory() . '/lib/modules/' ) : null; //add the lib portion to the URL
`
Really thankful you made this.

**Comment by lceberg** [comment]
Hey woodwardtw,

Thanks for the feedback!

As the theme is still in (quite early) development I guess I haven't documented this part. :)

Can you try the following:

- restore line 3 in functions.php to:
```
! defined( 'VUETIFUL_MODULES_DIR' ) ? define( 'VUETIFUL_MODULES_DIR', get_template_directory() . '/modules/' ) : null;
```
- create a "modules" directory in the root of the theme (I guess an empty folder doesn't get pushed to git)
- create a "Test" subdirectory folder with a module.php file in it
- go to Appearance > Modules in the dashboard, you should now see "Test" as a checkbox

The idea of that functionality is to have the ability to add your own custom code as modules - something like plugins within the theme. This way you can add custom functionality that you can easily turn on and off (and maybe use different things for different sites on multisite).

I started this theme as an experiment and it is far from complete, but feel free to test it and let me know if you have any feedback. In the meantime I will update the readme a bit.

**Comment by woodwardtw** [comment]
You are exactly correct. Sorry for the false alarm. This is my first round with Vue.
